version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_CONN: postgres://{postgres}:{1}@{localhost}:{5432}/{postgres}
      POSTGRES_PASSWORD: 1
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PGPASSWORD: 1
    depends_on:
      - db
    command: sh -c "sleep 10 && ./avito_service -ip 0.0.0.0 -port 8080"

volumes:
  postgres_data:
